export const header = {
  mobile: {
    wrapper: {
      position: "sticky",
      top: 0,
      zIndex: 50,
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "0.75rem 1rem",
      backgroundColor: "var(--color-bg-card)",
      borderBottom: "1px solid var(--color-border)",
      boxShadow: "var(--shadow-card)",
    },
    logo: {
      display: "flex",
      alignItems: "center",
      textDecoration: "none",
    },
    image: {
      width: "120px",
      height: "34px",
      objectFit: "cover",
      objectPosition: "center",
    },
    // On phones the nav drops to its own full-width row under the logo and actions.
    nav: {
      order: 3,
      width: "100%",
      display: "flex",
      justifyContent: "center",
      gap: "0.25rem",
      marginTop: "0.6rem",
      paddingTop: "0.6rem",
      borderTop: "1px solid var(--color-border)",
    },
    right: {
      display: "flex",
      alignItems: "center",
      gap: "0.6rem",
    },
    signIn: {
      background: "transparent",
      border: "1px solid var(--color-accent)",
      padding: "0.4rem 0.8rem",
      borderRadius: "8px",
      cursor: "pointer",
      color: "var(--color-accent)",
    },
    avatarButton: {
      display: "flex",
      padding: 0,
      border: "none",
      background: "none",
      borderRadius: "50%",
      cursor: "pointer",
    },
    userName: {
      color: "var(--color-text-secondary)",
      fontSize: "0.9rem",
      fontWeight: 500,
    },
    signOut: {
      background: "transparent",
      border: "1px solid var(--color-border-strong)",
      padding: "0.4rem 0.8rem",
      borderRadius: "8px",
      cursor: "pointer",
      color: "var(--color-text-primary)",
    },
  },
  desktop: {
    wrapper: {
      flexWrap: "nowrap",
      padding: "0.9rem 4rem",
    },
    image: {
      width: "150px",
      height: "42px",
      objectFit: "cover",
      objectPosition: "center",
    },
    nav: {
      order: 0,
      width: "auto",
      flex: 1,
      justifyContent: "flex-start",
      marginTop: 0,
      marginLeft: "2.5rem",
      paddingTop: 0,
      borderTop: "none",
    },
    right: {
      gap: "0.9rem",
    },
  },
};
