export const homePage = {
  mobile: {
    wrapper: {
      display: "flex",
      flexDirection: "column",
      minHeight: "100vh",
      backgroundColor: "var(--color-bg-page)",
    },
    content: {
      flex: 1,
      padding: "1.2rem",
      marginTop: "1rem",
    },
    card: {
      backgroundColor: "var(--color-bg-card)",
      borderRadius: "20px",
      padding: "1.5rem",
      border: "1px solid var(--color-border)",
      boxShadow: "var(--shadow-card)",
      display: "flex",
      flexDirection: "column",
      gap: "1.2rem",
    },
    title: {
      fontSize: "1.6rem",
      fontWeight: 800,
      fontFamily: "var(--font-heading)",
      letterSpacing: "-0.5px",
      textAlign: "center",
      color: "var(--color-text-primary)",
    },
    subtext: {
      fontSize: "0.9rem",
      textAlign: "center",
      color: "var(--color-text-secondary)",
      marginBottom: "0.5rem",
    },
    form: {
      display: "flex",
      flexDirection: "column",
      gap: "1rem",
    },
    verifyBanner: {
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
      gap: "0.6rem",
      padding: "0.9rem 1rem",
      borderRadius: "12px",
      border: "1px solid var(--color-accent)",
      backgroundColor: "var(--color-accent-soft)",
    },
    verifyText: {
      margin: 0,
      fontSize: "0.9rem",
      color: "var(--color-text-primary)",
    },
    charCount: {
      fontSize: "0.75rem",
      textAlign: "right",
      color: "var(--color-text-secondary)",
      marginTop: "-0.6rem",
    },
    charCountOver: {
      color: "var(--color-danger, #dc2626)",
      fontWeight: 600,
    },
    fieldGroup: {
      display: "flex",
      flexDirection: "column",
      gap: "0.4rem",
    },
    fieldLabel: {
      fontSize: "0.85rem",
      fontWeight: 500,
      color: "var(--color-text-secondary)",
    },
    select: {
      width: "100%",
      padding: "0.7rem 0.9rem",
      borderRadius: "10px",
      border: "1px solid var(--color-border)",
      backgroundColor: "var(--color-bg-input)",
      color: "var(--color-text-primary)",
      fontSize: "0.9rem",
    },
    errorText: {
      fontSize: "0.9rem",
      color: "var(--color-danger)",
      textAlign: "center",
    },
    progressWrap: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: "1rem",
      padding: "2rem 0",
    },
    stepText: {
      fontSize: "0.95rem",
      color: "var(--color-text-secondary)",
      textAlign: "center",
    },
    resultActions: {
      display: "flex",
      flexDirection: "column",
      gap: "0.75rem",
    },
  },

  desktop: {
    wrapper: {
      display: "flex",
      flexDirection: "column",
      minHeight: "100vh",
      backgroundColor: "var(--color-bg-page)",
    },
    content: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: "3rem 4rem 0",
    },
    card: {
      backgroundColor: "var(--color-bg-card)",
      width: "60%",
      maxWidth: "700px",
      borderRadius: "24px",
      padding: "2.5rem",
      border: "1px solid var(--color-border)",
      boxShadow: "var(--shadow-card)",
      display: "flex",
      flexDirection: "column",
      gap: "1.5rem",
      transition: "0.3s ease",
    },
    title: {
      fontSize: "2.2rem",
    },
    subtext: {
      fontSize: "1rem",
      marginBottom: "0.5rem",
    },
    form: {
      display: "flex",
      flexDirection: "column",
      gap: "1.2rem",
    },
    resultActions: {
      flexDirection: "row",
      flexWrap: "wrap",
    },
  },
};
