export const homePage = {
  mobile: {
    wrapper: {
      display: "flex",
      flexDirection: "column",
      minHeight: "100vh",
      backgroundColor: "var(--color-bg-page)",
    },
    content: {
      flex: 1,
      padding: "1.2rem",
      marginTop: "1rem",
    },
    card: {
      backgroundColor: "var(--color-bg-card)",
      borderRadius: "20px",
      padding: "1.5rem",
      border: "1px solid var(--color-border)",
      boxShadow: "var(--shadow-card)",
      display: "flex",
      flexDirection: "column",
      gap: "1.2rem",
    },
    title: {
      fontSize: "1.6rem",
      fontWeight: 800,
      fontFamily: "var(--font-heading)",
      letterSpacing: "-0.5px",
      textAlign: "center",
      color: "var(--color-text-primary)",
    },
    subtext: {
      fontSize: "0.9rem",
      textAlign: "center",
      color: "var(--color-text-secondary)",
      marginBottom: "0.5rem",
    },
    form: {
      display: "flex",
      flexDirection: "column",
      gap: "1rem",
    },
    charCount: {
      fontSize: "0.75rem",
      textAlign: "right",
      color: "var(--color-text-secondary)",
      marginTop: "-0.6rem",
    },
    charCountOver: {
      color: "var(--color-danger, #dc2626)",
      fontWeight: 600,
    },
    result: {
      marginTop: "1.2rem",
      backgroundColor: "var(--color-bg-card)",
      borderRadius: "20px",
      padding: "1.5rem",
      border: "1px solid var(--color-border)",
      boxShadow: "var(--shadow-card)",
      display: "flex",
      flexDirection: "column",
      gap: "0.75rem",
    },
    resultTitle: {
      fontSize: "1.1rem",
      fontWeight: 700,
      fontFamily: "var(--font-heading)",
      color: "var(--color-text-primary)",
    },
    resultText: {
      fontSize: "0.95rem",
      lineHeight: 1.7,
      whiteSpace: "pre-wrap",
      color: "var(--color-text-secondary)",
    },
  },

  desktop: {
    wrapper: {
      display: "flex",
      flexDirection: "column",
      minHeight: "100vh",
      backgroundColor: "var(--color-bg-page)",
      padding: "2rem 4rem",
    },
    content: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      paddingTop: "1rem",
    },
    card: {
      backgroundColor: "var(--color-bg-card)",
      width: "60%",
      maxWidth: "700px",
      borderRadius: "24px",
      padding: "2.5rem",
      border: "1px solid var(--color-border)",
      boxShadow: "var(--shadow-card)",
      display: "flex",
      flexDirection: "column",
      gap: "1.5rem",
      transition: "0.3s ease",
    },
    title: {
      fontSize: "2.2rem",
    },
    subtext: {
      fontSize: "1rem",
      marginBottom: "0.5rem",
    },
    form: {
      display: "flex",
      flexDirection: "column",
      gap: "1.2rem",
    },
    result: {
      width: "60%",
      maxWidth: "700px",
      borderRadius: "24px",
      padding: "2.5rem",
      marginTop: "1.5rem",
    },
    resultTitle: {
      fontSize: "1.3rem",
    },
    resultText: {
      fontSize: "1.05rem",
    },
  },
};
