export const login = {
    mobile: {
        wrapper: {
            minHeight: "100vh",
            backgroundImage: "url(/images/nostalgic_image.avif)",
            backgroundSize: "cover",
            backgroundPosition: "center",
            display: "flex",
            flexDirection: "column",
            position: "relative",
        },
        backgroundOverlay: {
            position: "absolute",
            inset: 0,
            backgroundColor: "var(--overlay-glass-tint)",
            backdropFilter: "blur(8px)",
        },
        content: {
            zIndex: 1,
            flex: 1,
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            padding: "1.5rem",
        },
        card: {
            width: "100%",
            maxWidth: "420px",
            backgroundColor: "var(--overlay-glass-bg)",
            backdropFilter: "blur(10px)",
            padding: "2.5rem 2rem",
            borderRadius: "24px",
            boxShadow: "var(--shadow-modal)",
            border: "1px solid var(--color-border)",
        },
        title: {
            fontSize: "2rem",
            fontWeight: "800",
            fontFamily: "var(--font-heading)",
            color: "var(--color-text-primary)",
            letterSpacing: "-0.5px",
            marginBottom: "0.5rem",
        },
        subtitle: {
            color: "var(--color-text-secondary)",
            fontSize: "0.95rem",
        },
        errorAlert: {
            padding: "0.75rem",
            marginBottom: "1rem",
            borderRadius: "8px",
            backgroundColor: "var(--color-danger-soft)",
            color: "var(--color-danger)",
            border: "1px solid var(--color-danger)",
        },
        inputSection: {
            display: "flex",
            flexDirection: "column",
            gap: "1.2rem",
        },
        forgotLink: {
            fontSize: "0.8rem",
            color: "var(--color-accent)",
            textDecoration: "none",
            fontWeight: 600,
            float: "right",
            marginTop: "4px",
        },
        dividerContainer: {
            display: "flex",
            alignItems: "center",
            margin: "2rem 0",
        },
        dividerLine: { flex: 1, height: "1px", backgroundColor: "var(--color-border)" },
        dividerText: { padding: "0 10px", fontSize: "0.75rem", color: "var(--color-text-muted)", fontWeight: 700 },
        socialContainer: {
            wrapper: {
                display: "flex",
                flexDirection: "column",
                gap: "0.75rem",
                width: "100%",
            },
            googleWrapper: {
                display: "flex",
                justifyContent: "center",
                width: "100%",
            },
            socialErrorAlert: {
                width: "100%",
                padding: "0.5rem",
                marginBottom: "0.75rem",
                borderRadius: "8px",
                backgroundColor: "var(--color-danger-soft)",
                color: "var(--color-danger)",
                border: "1px solid var(--color-danger)",
                fontSize: "0.875rem",
                textAlign: "center" as const,
            },
            processingOverlay: {
                opacity: 0.6,
                pointerEvents: "none" as const,
            },
            socialButton: {
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                width: '100%',
                backgroundColor: '#1877F2',
                color: '#FFFFFF',
                border: 'none',
                borderRadius: '20px',
                padding: '2px 16px 2px 2px',
                cursor: 'pointer',
                height: '40px',
                fontFamily: 'Roboto, Arial, sans-serif',
                fontSize: '14px',
                fontWeight: '500',
            },
            socialButtonDisabled: {
                opacity: 0.6,
            },
            iconContainer: {
                backgroundColor: '#FFFFFF',
                borderRadius: '50%',
                width: '36px',
                height: '36px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                marginRight: '12px',
            },
            socialIcon: {
                width: '20px',
                height: '20px',
            },
            buttonText: {
                whiteSpace: 'nowrap',
            }
        },
        signupText: {
            textAlign: "center",
            marginTop: "2rem",
            fontSize: "0.9rem",
            color: "var(--color-text-secondary)",
        },
        link: { color: "var(--color-accent)", fontWeight: 700, textDecoration: "none" }
    },
    desktop: {
        card: { padding: "3rem" },
        socialIcon: { width: "24px", height: "24px" }
    }
}
